### ISSUE TITLE
Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by mnai01** [vercel/next-rsc-demo#5]
Repro Steps:
1. git clone
2. remove yarn from package.json so i can use npm to start
3. `npm run dev`

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at DevServer.renderError (C:\Users\Admin\Documents\Javascript\FullStack\Next.js-Strapi-Template\next-rsc-demo\node_modules\next\dist\server\next-server.js:1631:17)
    at DevServer.run (C:\Users\Admin\Documents\Javascript\FullStack\Next.js-Strapi-Template\next-rsc-demo\node_modules\next\dist\server\dev\next-dev-server.js:431:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
error - TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer. Received an instance of Uint8Array
error - unhandledRejection: undefined
error - unhandledRejection: TypeError: The stream (in errored state) is not in the writable state and cannot be closed
```

**Comment by shuding** [comment]
Could you clone the latest repo again? Thanks! I think we’ve fixed this issue.

**Comment by mnai01** [comment]
Updating node.js seemed to help too. Was using v12 and updated to LTS v16 and it worked fine
